// Generated by CoffeeScript 1.10.0
var defferredActions;

defferredActions = angular.module('defferredActions', []);

defferredActions.controller('waitTimer', function($scope, $timeout) {
  var butWidth, timerValue;
  $scope.app = "Приложение работает!";
  $scope.wait = {};
  $scope.wait.active = false;
  $scope.intID = 0;
  $scope.pr = 0;
  timerValue = 5;
  butWidth = 40;
  $scope.styles = {
    "progressButton": {
      "width": butWidth + "px"
    },
    "shutter": {
      "left": butWidth + "px"
    }
  };
  $scope.animate = function() {
    var c, myTimer;
    if ($scope.wait.active) {
      $scope.wait.active = false;
      $timeout.cancel($scope.pr);
    } else {
      $scope.wait.timer = timerValue;
      $scope.wait.active = true;
      $scope.wait.transparent = "transparent";
      $scope.app = "Таймер запущен";
      c = timerValue;
      myTimer = function() {
        if (c === 0) {
          console.log("Время вышло!");
          return;
        }
        $scope.wait.timer = c;
        c--;
        $scope.pr = $timeout(function() {
          myTimer();
        }, 1000);
      };
      myTimer();
    }
  };
});
