// Generated by CoffeeScript 1.10.0
var defferredActions;

defferredActions = angular.module('defferredActions', []);

defferredActions.controller('waitTimer', function($scope, $timeout) {
  $scope.app = "Приложение работает!";
  $scope.wait = {};
  $scope.wait.active = false;
  $scope.wait.timerVal = 5;
  $scope.intID = 0;
  $scope.pr = 0;
  $scope.animate = function() {
    var c, myTimer;
    if ($scope.wait.active) {
      $scope.wait.active = false;
      $timeout.cancel($scope.pr);
    } else {
      $scope.wait.timer = $scope.wait.timerVal = 5;
      $scope.wait.active = true;
      $scope.app = "Таймер запущен";
      c = $scope.wait.timerVal;
      myTimer = function() {
        if (c === 0) {
          console.log("Время вышло!");
          return;
        }
        $scope.wait.timer = c;
        c--;
        $scope.pr = $timeout(function() {
          myTimer();
        }, 1000);
      };
      myTimer();
    }
  };
  $scope.setTime = function(t) {
    $scope.wait.timer = t;
  };
});
